### ISSUE TITLE
Problem when running on Archlinux tensorflow-opt-cuda

### ISSUE THREAD

**Issue by p-h** [pkgw/elfx86exts#2]
I tried running it on libtensorflow.so from [this package](https://www.archlinux.org/packages/community/x86_64/tensorflow-opt-cuda/) (version: 1.8.0-5) and it froze my entire computer. The sha224sum of the file is 8f665acf0f455d5056014dfa2d48c22ab6cf83eb073842e8304878d0

**Comment by HanabishiRecca** [comment]
I think this is due to #90. As the lib has an insane size around 1GB, OOM simply caused the computer to freeze.

With the fix from #173 applied, it reads totally fine for me:
```
$ elfx86exts libtensorflow.so.2.13.0
File format and CPU architecture: Elf, X86_64
MODE64 (call)
AVX (vzeroupper)
CMOV (cmovne)
NOVLX (vpxor)
AVX2 (vinserti128)
SSE1 (prefetcht2)
BMI (tzcnt)
SSE2 (movq)
SSE41 (pmovzxbw)
SSE42 (crc32)
NOT64BITMODE (xchg)
Instruction set extensions used: AVX, AVX2, BMI, CMOV, MODE64, NOT64BITMODE, NOVLX, SSE1, SSE2, SSE41, SSE42
CPU Generation: Unknown
```
