### ISSUE TITLE
New release to support Debian packaging of elfx86exts?

### ISSUE THREAD

**Issue by mr-c** [pkgw/elfx86exts#31]
Hello,

I'm packaging `elfx86exts` for Debian and it would be helpful if you could make a release with your updated dependency on the newer `capstone` cargo version 0.7

https://salsa.debian.org/rust-team/debcargo-conf/-/merge_requests/108

Thanks!

**Comment by pkgw** [comment]
Sure thing. Version 0.4.0, now on crates.io and GitHub. I'll close this issue but please feel free to reopen or comment if you have any follow-ups.

**Comment by pkgw** [comment]
PS. Also, if you wouldn't mind submitting a PR to add the Debian info to the README.md once the package is finalized, that would be great!

**Comment by mr-c** [comment]
A 2021 update: the review for entry into the Debian development distribution has been queued up! https://ftp-master.debian.org/new/rust-elfx86exts_0.3.0-1.html

**Comment by pkgw** [comment]
Thanks for the update!
